import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — LocalGenius',
  description: 'Terms governing your use of LocalGenius.',
};

export default function TermsPage() {
  return (
    <div className="px-screen-margin py-16 max-w-[720px] mx-auto">
      <h1 className="text-[2rem] font-semibold text-charcoal leading-tight mb-8">
        Terms of Service
      </h1>
      <p className="text-caption text-slate mb-8">Last updated: April 2, 2026</p>

      <div className="flex flex-col gap-8 text-body text-slate leading-relaxed">
        <section>
          <h2 className="text-h2 text-charcoal mb-3">The service</h2>
          <p>LocalGenius provides AI-powered marketing assistance for local businesses, including content generation, review management, website creation, and weekly performance digests. The service is provided as-is.</p>
        </section>

        <section>
          <h2 className="text-h2 text-charcoal mb-3">Your account</h2>
          <p>You are responsible for maintaining the security of your account. You must provide accurate business information. You may not use the service for any illegal purpose or to generate misleading content about your business.</p>
        </section>

        <section>
          <h2 className="text-h2 text-charcoal mb-3">Content ownership</h2>
          <p>Content generated by LocalGenius for your business belongs to you. You grant LocalGenius a license to use your business information solely to provide the service. We may display your business name and a "Made with LocalGenius" attribution on generated websites.</p>
        </section>

        <section>
          <h2 className="text-h2 text-charcoal mb-3">AI-generated content</h2>
          <p>Content is generated by AI and reviewed before publication. However, you are responsible for approving all content before it goes live. LocalGenius is not liable for AI-generated content that you approve and publish.</p>
        </section>

        <section>
          <h2 className="text-h2 text-charcoal mb-3">Pricing and billing</h2>
          <p>Base plan: $29/month. Pro plan: $79/month. No contracts — cancel anytime. Prices may change with 30 days notice. Refunds are handled on a case-by-case basis.</p>
        </section>

        <section>
          <h2 className="text-h2 text-charcoal mb-3">Cancellation</h2>
          <p>You can cancel your account at any time. Your data will be retained for 30 days after cancellation, then permanently deleted. Generated websites will be taken offline within 24 hours of cancellation.</p>
        </section>

        <section>
          <h2 className="text-h2 text-charcoal mb-3">Limitation of liability</h2>
          <p>LocalGenius is provided as-is without warranty. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability is limited to the amount you paid in the 12 months preceding any claim.</p>
        </section>

        <section>
          <h2 className="text-h2 text-charcoal mb-3">Contact</h2>
          <p>Questions about these terms? Email hello@localgenius.company.</p>
        </section>
      </div>
    </div>
  );
}
